# Generated by Django 3.2.7 on 2021-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='foto'),
        ),
    ]
