# Generated by Django 3.2.7 on 2021-12-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20211123_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='photo',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='foto'),
        ),
    ]
